FROM jetlinks/base-jdk-21
# 确保是非交互模式
ENV DEBIAN_FRONTEND=noninteractive
# 使用清华源（推荐，国内速度快，自动适配架构）
## 适用于 Ubuntu 24.04 (noble) ARM64，使用清华的 ubuntu-ports 源
#RUN echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble main restricted universe multiverse" > /etc/apt/sources.list && \
#    echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
#    echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble-backports main restricted universe multiverse" >> /etc/apt/sources.list && \
#    echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble-security main restricted universe multiverse" >> /etc/apt/sources.list


# 更新软件源并安装编译工具与依赖库
# 参考https://github.com/ZLMediaKit/ZLMediaKit/blob/master/docker/ubuntu18.04/Dockerfile.devel
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    wget \
    cmake \
    git \
    curl \
    vim \
    ca-certificates \
    tzdata \
    libsrtp2-1 \
    libssl-dev \
    libmysqlclient-dev \
    libx264-dev \
    libfaac-dev \
    ffmpeg && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

# 手动下载这个依赖库
# 仅当目标架构是 arm64 时，才下载并安装 libssl1.1
ARG TARGETARCH
RUN if [ "${TARGETARCH}" = "arm64" ]; then \
      wget http://ports.ubuntu.com/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_arm64.deb && \
      dpkg --force-depends -i libssl1.1_1.1.1f-1ubuntu2.24_arm64.deb; \
    fi

# 确认安装
RUN ldconfig

